name: Test
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: levelup
      - name: Build
        run: g++ -std=c++17 *.cpp -o output
      - name: Test
        run: ./tests.sh
      - name: cppcheck
        uses: deep5050/cppcheck-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          github_username: "tamasori"
          github_email: "oeri.tamas@gmail.com"
          commit_msg: "CPPCHECK log"
          enable: "style,warning,performance,portability,unusedFunction,missingInclude"
