name: Test
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: balintxd/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: CPPCheck Static Code Analysis
        run: make sca
      - name: Upload CPPCheck report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_report
          path: cppcheck_report.txt
      - name: Build
        run: make
      - name: Valgrind memory check
        run: make valgrind
      - name: In-Out tests
        run: make outputtest
