name: Test
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: levelup
      - name: Build
        run: g++ -std=c++17 *.cpp -o output
      - name: Test
        run: ./tests.sh
