name: Unit Tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: balintxd/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cd tests && cmake . && make
      - name: Run Tests
        run: make unittests
